[package]
name = "dart_todo"
version = "0.1.0"
edition = "2024"

[lib]
name = "dart_todo"
crate-type = ["cdylib", "rlib"]

[dependencies]
todo = { path = "../todo", features = ["dart"] }
flutter_rust_bridge = { workspace = true }

