[workspace]
resolver = "3"
members = [
    "crates/todo",
]
exclude = [
    "crates/py-todo",
]

[workspace.dependencies]
chrono = { version = "0.4", features = ["serde"] }
async-trait = "0.1"
uuid = { version = "1.0", features = ["v4"] }
pyo3 = "0.27.2"